---
- hosts: all
  tasks:
  - name: Add epel repository
    yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
